import classNames from 'classnames'
import './globals.css'
import { Urbanist } from 'next/font/google'
import localFont from 'next/font/local'

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-body',
})
const madeGentle = localFont({
  src: './MADE Gentle.otf',
  variable: '--font-display',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          'bg-gunmetal text-white',
          `${urbanist.variable} ${madeGentle.variable} font-body`
        )}
      >
        {children}
      </body>
    </html>
  )
}
